config/routes.rb
BeardedNemesis::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :solar_systems, :only => [:index, :show]
  resources :minerals
  resources :moons

  resources :home, :only => [:index] do
  	get "health_check", on: :collection
  end
  
  namespace :admin do
    resources :users, :only => [:index, :update]
  end

  root :to => 'home#index'

end

app/models/moon.rb
class Moon < ActiveRecord::Base
  attr_accessible :celestial_id, :location_id, :name, :updated_by_id
  
  has_and_belongs_to_many :minerals
  belongs_to :user
  
  validates :name,          :presence => true, :uniqueness => true
  validates :celestial_id,  :presence => true, numericality: { only_integer: true }, :uniqueness => true
  validates :location_id,   :presence => true, numericality: { only_integer: true }
  
  scope :by_location_id, lambda { |value| where("location_id = ?", value) if value }
  scope :by_mineral_type_id, lambda { |value| joins(:minerals).where("type_id = ?", value) if value }
  
  def created_by
    @submitter ||= User.find(user_id)
  end
  
  def updated_by
    @updater ||= User.find(updated_by_id)
  end
  
  def self.search(params)
    moons = Moon.order(:celestial_id)
                 .by_location_id(params[:location_id])
                 .by_mineral_type_id(params[:mineral_type_id])
                 .page(params[:page]).per(params[:limit])
  end
end

app/controllers/moons_controller.rb
class MoonsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /moons
  # GET /moons.json
  def index
    authorize! :index, Moon
    @moons = Moon.search(params)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moons }
    end
  end

  # GET /moons/1
  # GET /moons/1.json
  def show
    authorize! :show, Moon
    @moon = Moon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @moon }
    end
  end

  # GET /moons/new
  # GET /moons/new.json
  def new
    authorize! :new, Report
    @moon = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @moon }
    end
  end

  # GET /moons/1/edit
  def edit
    authorize! :edit, Report
    @moon = Moon.find(params[:id])
  end

  # POST /moons
  # POST /moons.json
  def create
    authorize! :create, Report
    @moon = Report.new(params[:moon])

    respond_to do |format|
      if @moon.save
        format.html { redirect_to @moon.moon, notice: 'Moon was successfully created.' }
        format.json { render json: @moon.moon, status: :created, location: @moon.moon }
      else
        format.html { render action: "new" }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moons/1
  # PUT /moons/1.json
  def update
    authorize! :update, Moon
    @moon = Moon.find(params[:id])

    respond_to do |format|
      if @moon.update_attributes(params[:moon])
        format.html { redirect_to @moon, notice: 'Moon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moons/1
  # DELETE /moons/1.json
  def destroy
    authorize! :destroy, Moon
    @moon = Moon.find(params[:id])
    @moon.destroy

    respond_to do |format|
      format.html { redirect_to moons_url }
      format.json { head :no_content }
    end
  end
end

app/views/moons/_form.html.erb
<%= form_for @moon, :url => moons_path, :as => :moon do |f| %>
  <% if @moon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moon.errors.count, "error") %> prohibited this moon from being saved:</h2>

      <ul>
      <% @moon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_name %><br />
    <%= f.text_field :location_name, :autocomplete => :off, :placeholder => "solar system name", :data => { :provide =>"typeahead" }, :value => params[:location_name] %>
  </div>
  <div class="field">
    <%= f.label :moon_name %><br />
    <select id="moon_celestial_id" name="moon[celestial_id]"></select>
  </div>
  <div class="field">
    <%= f.label :mineral_1 %><br />
    <%= collection_select(:moon, :mineral_name_1, Mineral.all, :id, :name, {prompt: 'Select Mineral'}) %>
  </div>
  <div class="field">
    <%= f.label :mineral_2 %><br />
    <%= collection_select(:moon, :mineral_name_2, Mineral.all, :id, :name, {prompt: 'Select Mineral'}) %>
  </div>
  <div class="field">
    <%= f.label :mineral_3 %><br />
    <%= collection_select(:moon, :mineral_name_3, Mineral.all, :id, :name, {prompt: 'Select Mineral'}) %>
  </div>
  <div class="field">
    <%= f.label :mineral_4 %><br />
    <%= collection_select(:moon, :mineral_name_4, Mineral.all, :id, :name, {prompt: 'Select Mineral'}) %>
  </div>
  
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :moon_name, :value => params[:location_name] %>
  <%= f.hidden_field :location_id, :value => params[:location_id] %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moons/edit.html.erb
<h1>Editing moon</h1>

<%= render 'form' %>

<%= link_to 'Show', @moon %> |
<%= link_to 'Back', moons_path %>

app/views/moons/index.html.erb
<div id="moons-index">
  <h1>Listing moons</h1>

  <%= link_to 'New Moon', new_moon_path, :class => "btn btn-primary" %>
  
  <div class="pull-right">
    <%= form_tag("/moons", :method => :get, :class => "navbar-form") do %>
      <%= text_field_tag :location_name, nil, :placeholder => "solar system name", :autocomplete => :off, :data => { :provide =>"typeahead" }, :class => "search-query" %>
      <%= hidden_field_tag :location_id %>
      <%= submit_tag "Search" %>
    <% end %>
    <br />
  </div>
  
  <table id="all-moons" class="table table-condensed table-hover table-striped">
    <tr>
      <th>Celestial</th>
      <th>Name</th>
      <th>Location</th>
    </tr>

  <% @moons.each do |moon| %>
    <tr class="moon">
      <td><%= moon.celestial_id %></td>
      <td><%= link_to "#{moon.name}", moon %></td>
      <td id="<%= moon.location_id %>" class="moon-location-name"><%= link_to "#{moon.location_id}", solar_system_path(moon.location_id) %></td>
    </tr>
  <% end %>
  
  <% if @moons.empty? %>
    <tr class="error">
      <td colspan="3">No results found.</td>
    <tr>
  <% end %>
  </table>
  <%= paginate @moons %>
</div>

app/views/moons/new.html.erb
<h1>New moon</h1>

<%= render 'form' %>

<%= link_to 'Back', moons_path %>

app/views/moons/show.html.erb
<div id="moon-info">
  <div id="moon-name"><b><%= @moon.name %></b> (ID:<%= @moon.celestial_id %>)</div>
  <div id="moon-location">Location: <span id="<%= @moon.location_id %>"><%= link_to "#{@moon.location_id}", solar_system_path(@moon.location_id) %></span></div>
  <div id="moon-submitter">Submitted by: <%= @moon.created_by.name %> on <%= @moon.created_at %></div>
  <div id="moon-updater">Updated by: <%= @moon.updated_by.name %> on <%= @moon.updated_at %></div>
</div>

<b>Minerals</b>
<div id="moon-minerals">
  <% @moon.minerals.each do |mineral| %>
    <div><%= link_to "#{mineral.name}", mineral %></div>
  <% end %>
</div>

<div id="add-moon"></div>

<br />
<%= link_to 'Back', moons_path, :class => "btn" %> | 
<%= link_to 'Edit', edit_moon_path(@moon), :class => "btn" %> | 
<%= link_to 'Destroy', @moon, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>