config/routes.rb
BeardedNemesis::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :solar_systems, :only => [:index, :show]
  resources :minerals
  resources :moons

  resources :home, :only => [:index] do
  	get "health_check", on: :collection
  end
  
  namespace :admin do
    resources :users, :only => [:index, :update]
  end

  root :to => 'home#index'

end

app/views/layouts/_messages.html.erb
<div id="flash-messages">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to "Bearded Nemesis", root_path, :class => 'brand' %>
<ul class="nav">
  <li><%= link_to 'Moons', moons_path %></li>
  <li><%= link_to 'Moon Minerals', minerals_path %></li>
  <li><%= link_to 'Solar Systems', solar_systems_path %></li>
  
  <% if can? :manage, User %>
    <li><%= link_to 'Admin', admin_users_path %></li>
  <% end %>
  
  <% if user_signed_in? %>
    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bearded Nemesis" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tracking moons for great profit" %>">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>